### PR TITLE
Use NPM package for Leanplum JS SDK

### PR DESCRIPTION
**Pull request by gyoshev**
Currently the integration requests the Leanplum JS SDK from the Leanplum site, once the integration is loaded. The used URL is not documented and could break without notice, and is not using the latest version of the SDK.

This PR starts using NPM to fetch the latest SDK version, and removes the latency when loading it.

As a testing strategy, I ran the available unit tests.

### CODE REVIEW

**Comment by rmi22186** [comment]
Hi @gyoshev - thanks for the PR!  Interesting, I definitely pulled that url from a Leanplum doc in the past when I originally built this integration. Anyhow, combing through your docs, I now see that it can be loaded via [jsdelivr](https://docs.leanplum.com/reference#section-using-a-cdn). Some of our clients _may_ include leanplum before mparticle themselves (just from legacy), which would result in loading leanplum twice if it's built. We could add a check so that it doesn't fetch if it already exists.

What do you think about having it fetch from jsdelivr and check to see if it exists first?  It's a tradeoff between increasing the size of the integration here vs fetching via another API call.  Because we queue events if leanplum isnt loaded yet, there shouldn't less of an issue wrt latency. Let me know what you think of this approach?

**Comment by gyoshev** [comment]
@rmi22186 good point about the double loading. I've recycled the PR to load from jsdelivr. 🙂

**Comment by gyoshev** [comment]
@rmi22186 I also added a check if the lib is already loaded, as discussed.

**Comment by rmi22186** [comment]
Hi @gyoshev -

Thanks for updating that all.  We actually recently modified out build processes with a github action that will build and bundle the files, and deploy to NPM once we update the version number. Can you only include the `src/LeanplumAnalyticsEventForwarder.js` file in this PR? This was a recent change and not yet reflectedin the Readme, which also needs updating across our integrations.

Thanks!

**Comment by gyoshev** [comment]
@rmi22186 Done!

**Comment by rmi22186** [comment]
@gyoshev - Thanks! This looks good. We don't do Friday releases so I'll merge this on Monday.

**Comment by rmi22186** [comment]
Hi @gyoshev -
This has been released and is now live for all of our mutual clients. It has been updated on [NPM](https://www.npmjs.com/package/@mparticle/web-leanplum-kit) as well for clients who self host mParticle.

Thanks again for your input :)

**Pull request merged**
